# You're on your own for this one.
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# ...
# Okay fine. The entire bash_exercises.sh solution script will be uploaded after the tutorial.