install.packages(c("dplyr","effects", "ggpubr", "ggthemes", "interactions", "psych", "plyr", "rstatix", 
"RColorBrewer", "report", "sjPlot", "sjstats", "skimr", "stargazer", "tidyverse", "pwr"))

libary(dplyr)
library(effects) 
library(ggpubr)  
library(ggthemes)  
library(interactions)  
library(psych)  
library(plyr)  
library(rstatix)
library(RColorBrewer) 
library(report)
library(sjPlot)
library(sjstats)
library(skimr) 
library(stargazer)
library(tidyverse)
